export const UI_ELEMENTS = {
  MENU_BUTTON: document.querySelector('.menu-btn'),
  MENU_LIST: document.querySelector('.menu__list'),
  MENU_LINKS: document.querySelectorAll('.menu__list-link'),
  MODAL_WINDOW: document.querySelector('.modal'),
  MODAL_TEXT_FIELD: document.querySelector('.modal__text'),
  FORM: document.getElementById('form'),
  QUIZ_ANSWER_BUTTONS: document.querySelectorAll('.quiz__answer'),
  QUIZ_HEADER: document.querySelector('.quiz__box-header'),
  QUIZ_QUESTION: document.querySelector('.quiz__question'),
  QUIZ_ANSWER_A: document.querySelector('.quiz__text-a'),
  QUIZ_ANSWER_B: document.querySelector('.quiz__text-b'),
  QUIZ_ANSWER_C: document.querySelector('.quiz__text-c'),
  QUIZ_ANSWER_D: document.querySelector('.quiz__text-d'),
  QUIZ_NEXT_BUTTON: document.querySelector('.quiz__btn'),
  QUIZ_PAGINATION: document.querySelector('.quiz__pagination'),
  QUIZ_CLOSE_CROSS: document.querySelector('.quiz__close-cross'),
  QUIZ_CLOSE_BUTTON: document.querySelector('.quiz__close-btn'),
  QUIZ_START_BUTTON: document.querySelector('.header__btn'),
  QUIZ_CONTAINER: document.querySelector('.quiz'),
};
